# Generated by Django 4.1.6 on 2023-08-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.SlugField(max_length=20),
        ),
    ]
