# Generated by Django 4.1.6 on 2023-08-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='total_item',
        ),
    ]
