# Generated by Django 4.1.6 on 2023-08-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0002_remove_cartitems_total_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='Product',
            new_name='product',
        ),
    ]
